// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function() {
    this.loadTasks("build/tasks");
    this.registerTask("development", ["watch:css", "watch:coffee"]);
    return this.registerTask("default", ["clean", "coffee:build"]);
  };

}).call(this);

//# sourceMappingURL=Gruntfile.js.map
