// Generated by CoffeeScript 1.8.0
(function() {
  define(function(require) {
    var API, App, Loading, Model, loadingView, msgBus;
    App = require('app');
    msgBus = require('msgbus.coffee');
    Loading = require('views/spinner');
    loadingView = new Loading();
    return Model = Backbone.Model.extend({
      defaults: {
        id: null,
        trainerId: null,
        startDate: null,
        endDate: null,
        sessionTypeId: null,
        message: null
      },
      url: function() {
        return App.APIEndpoint + 'update';
      }
    }, API = {

      /**
      * @name updateAppointment
      * @function
      * @returns {object} promise object
       */
      updateAppointment: function(data) {
        var deferred, model;
        model = new Model();
        deferred = $.Deferred();
        App.layout.content.show(loadingView);
        model.save(data, {
          success: deferred.resolve,
          error: deferred.reject
        });
        return deferred.promise();
      }
    }, msgBus.reqres.setHandler('entities:update:appointment', function(data) {
      return API.updateAppointment(data);
    }));
  });

}).call(this);

//# sourceMappingURL=update.js.map
